### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by DraymondHIT** [cgraywang/deepstruct#1]
Hi, thanks for your paper and it's really a nice work!

May I know when will the code be released?

**Comment by mxq15** [comment]
May I know when will the code be released?

**Comment by XiaoqingNLP** [comment]
@cgraywang

**Comment by hjerbii** [comment]
Hello,

@cgraywang is it possible to know when you'll release the code?

Thanks in advance!

**Comment by XiaoqingNLP** [comment]
Waiting for so long, the author may not release it, there is an email to the author?

**Comment by qige96** [comment]
7 months later......

**Comment by Xiao9905** [comment]
The code and corresponding data processing scripts have been released. Thanks for you patience.
